# Generated by Django 4.0.2 on 2022-04-27 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0007_alter_workert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentt',
            name='base_pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
