# Generated by Django 4.0.2 on 2022-04-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0009_alter_assignmentt_aproject_alter_assignmentt_aworker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentt',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignmentt',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignmentt',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='assignmentt',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
