# Generated by Django 4.0.2 on 2022-04-30 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0010_alter_assignmentt_biodata_alter_assignmentt_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentt',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to='biodata'),
        ),
        migrations.AlterField(
            model_name='assignmentt',
            name='contract',
            field=models.FileField(blank=True, null=True, upload_to='contract'),
        ),
        migrations.AlterField(
            model_name='assignmentt',
            name='medical_report',
            field=models.FileField(blank=True, null=True, upload_to='medreport'),
        ),
        migrations.AlterField(
            model_name='assignmentt',
            name='nbi_clearance',
            field=models.FileField(blank=True, null=True, upload_to='nbi'),
        ),
    ]
