# Generated by Django 4.0.2 on 2022-05-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0011_alter_assignmentt_biodata_alter_assignmentt_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usert',
            name='password',
            field=models.CharField(max_length=10000),
        ),
    ]
