# Generated by Django 4.0.2 on 2022-05-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0012_alter_usert_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationreportt',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
