# Generated by Django 4.0.2 on 2022-05-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0013_alter_evaluationreportt_overall_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectt',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
