# Generated by Django 4.0.2 on 2022-05-21 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0014_projectt_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentt',
            name='biodata',
        ),
        migrations.AddField(
            model_name='workert',
            name='biodata',
            field=models.FileField(blank=True, null=True, upload_to='biodata'),
        ),
    ]
