# Generated by Django 4.0.2 on 2022-05-21 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hris', '0015_remove_assignmentt_biodata_workert_biodata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationreportt',
            name='eassignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hris.assignmentt'),
        ),
    ]
